version: "3.1"

services:
  mysql:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
#  flask:
#    image: flask_app_demo:latest
#    restart: always
#    environment:
#      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
#      MYSQL_DB_NAME: demo
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    volumes:
#      - ./data/flask_app/logs:/flask_app/logs
#      - ./data/flask_app/upload:/flask_app/upload
#    ports:
#      - 10001:10001
#    depends_on:
#      - mysql
#    links:
#      - mysql
